FROM library/alpine:3.6
MAINTAINER Borodin Gregory <grihabor@mail.ru>

RUN apk update \
 && apk add --no-cache \
        python3 \
        make \
        cmake \
        g++

ONBUILD ADD tests /project/tests
ONBUILD ADD test_files /project/test_files
ONBUILD ADD src /project/src

ONBUILD RUN mkdir /project/build \
 && cd /project/build \
 && CMAKE_MAKE_PROGRAM=make cmake /project/src \
 && make

CMD python3 /project/tests/run.py && cat /project/tests/results.csv

